import { useState } from "react";
import { assetUrl } from "@/lib/env";
import { cn } from "@/lib/utils";

type MediaImageProps = {
  src?: string | null;
  alt: string;
  width?: number;
  height?: number;
  lazy?: boolean;
  className?: string;
  fallbackSrc?: string;
  fallbackLabel?: string;
  /** Priority hint for the browser's resource scheduler. Use "high" for the LCP image on a page. */
  fetchPriority?: "high" | "low" | "auto";
  /** The `sizes` attribute to pair with the auto-generated `srcSet`. Defaults to "100vw". */
  sizes?: string;
};

// Width variants generated by scripts, e.g. `/images/hero-kitchen-480.webp`.
// Keep in sync with the widths passed to cwebp when regenerating images.
const RESPONSIVE_WIDTHS = [480, 960, 1536] as const;

function resolveSrc(src?: string | null): string | undefined {
  if (!src) return undefined;
  if (src.startsWith("http://") || src.startsWith("https://") || src.startsWith("data:")) {
    return src;
  }
  return assetUrl(src);
}

/** Local `/images/*.webp` assets follow a `<name>-<width>.webp` naming convention for responsive variants. */
function isResponsiveCandidate(src?: string | null): src is string {
  return !!src && src.startsWith("/images/") && src.endsWith(".webp");
}

function buildSrcSet(src: string): string {
  const base = src.slice(0, -".webp".length);
  return RESPONSIVE_WIDTHS.map((w) => `${assetUrl(`${base}-${w}.webp`)} ${w}w`).join(", ");
}

export function MediaImage({
  src,
  alt,
  width,
  height,
  lazy = true,
  className,
  fallbackSrc,
  fallbackLabel,
  fetchPriority,
  sizes = "100vw",
}: MediaImageProps) {
  const responsive = isResponsiveCandidate(src);
  const defaultSrc = responsive ? `${src.slice(0, -".webp".length)}-1536.webp` : src;
  const initial = resolveSrc(defaultSrc) ?? resolveSrc(fallbackSrc);
  const [failed, setFailed] = useState(!initial);

  if (failed || !initial) {
    return (
      <div
        className={cn("flex items-center justify-center bg-muted text-muted-foreground", className)}
        role="img"
        aria-label={alt}
      >
        <span className="px-4 text-center text-[10px] font-bold uppercase tracking-widest">
          {fallbackLabel ?? alt}
        </span>
      </div>
    );
  }

  return (
    <img
      src={initial}
      srcSet={responsive ? buildSrcSet(src) : undefined}
      sizes={responsive ? sizes : undefined}
      alt={alt}
      width={width}
      height={height}
      loading={lazy ? "lazy" : "eager"}
      fetchPriority={fetchPriority}
      decoding="async"
      className={className}
      onError={() => setFailed(true)}
    />
  );
}
