// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/atc-home/Current.tsx": () => import("../components/mockups/atc-home/Current.tsx"),
  "./components/mockups/atc-home/Editorial.tsx": () => import("../components/mockups/atc-home/Editorial.tsx")
};
