import { ArrowDownRight, ArrowUpRight, Menu, Plus, X } from "lucide-react";
import { useState, type ReactNode } from "react";

const assetRoot = "/__mockup/images/";
function Anchor({ href, children, className = "", onClick }: { href: string; children: ReactNode; className?: string; onClick?: () => void }) {
  return <a href={href} onClick={(e) => { e.preventDefault(); onClick?.(); }} className={`focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[#a33b2d] focus-visible:ring-offset-4 ${className}`}>{children}</a>;
}
function Wordmark({ inverse = false }: { inverse?: boolean }) {
  return <div className={`flex items-center gap-3 ${inverse ? "text-[#f5eee5]" : "text-[#2a211c]"}`}><span className="flex h-6 items-end gap-[3px]" aria-hidden="true"><i className={`h-3 w-[3px] -skew-x-12 ${inverse ? "bg-[#f5eee5]/70" : "bg-[#2a211c]/80"}`} /><i className={`h-5 w-[3px] -skew-x-12 ${inverse ? "bg-[#f5eee5]/70" : "bg-[#2a211c]/80"}`} /><i className="h-4 w-[3px] -skew-x-12 bg-[#a33b2d]" /></span><span className="font-serif text-[21px] uppercase leading-none tracking-[0.2em]"><span className={inverse ? "text-[#f5eee5]/60" : "text-[#2a211c]/60"}>A</span>mara</span><span className={`hidden border-l pl-3 text-[9px] uppercase tracking-[0.25em] sm:block ${inverse ? "border-[#f5eee5]/25 text-[#f5eee5]/60" : "border-[#2a211c]/20 text-[#2a211c]/55"}`}>Trading Center</span></div>;
}
function Kicker({ children, inverse = false }: { children: ReactNode; inverse?: boolean }) {
  return <div className={`flex items-center gap-3 text-[9px] font-semibold uppercase tracking-[0.24em] ${inverse ? "text-[#f5eee5]/60" : "text-[#2a211c]/55"}`}><span className={`h-px w-8 ${inverse ? "bg-[#f5eee5]/40" : "bg-[#a33b2d]"}`} />{children}</div>;
}
function ArrowLink({ children, href = "#" }: { children: ReactNode; href?: string }) {
  return <Anchor href={href} className="group inline-flex items-center gap-3 border-b border-[#a33b2d]/60 pb-2 text-[10px] font-semibold uppercase tracking-[0.2em] text-[#a33b2d] transition-colors hover:border-[#2a211c] hover:text-[#2a211c]">{children}<ArrowUpRight size={15} className="transition-transform group-hover:translate-x-1 group-hover:-translate-y-1" /></Anchor>;
}

export default function CatalogLead() {
  const [menuOpen, setMenuOpen] = useState(false);
  const [filter, setFilter] = useState("All");
  const filters = ["All", "Kitchen", "Wardrobe", "Fittings"];
  const products = [
    { name: "The Linea handle", type: "Fittings", detail: "Brushed nickel · 160 mm", image: "atc-hero-kitchen.jpg", tone: "#c1b3a1" },
    { name: "Pietra worktop", type: "Kitchen", detail: "Taj · honed quartz", image: "atc-showroom-wide.jpg", tone: "#766b60" },
    { name: "The Orlo pull", type: "Fittings", detail: "Burnished bronze · 96 mm", image: "atc-trade-workshop.jpg", tone: "#8d3d2f" },
    { name: "Nero tall unit", type: "Wardrobe", detail: "Lacquered oak · smoke", image: "atc-hero-kitchen.jpg", tone: "#34302c" },
  ];
  const shown = filter === "All" ? products : products.filter((p) => p.type === filter);
  return <div className="min-h-[100dvh] overflow-hidden bg-[#f3eee6] font-sans text-[#2a211c]">
    <header className="absolute inset-x-0 top-0 z-30"><div className="mx-auto flex max-w-[1440px] items-center justify-between px-6 py-6 md:px-12 md:py-8"><Anchor href="/" aria-label="Amara Trading Center home"><Wordmark /></Anchor><nav className="hidden items-center gap-8 md:flex">{[["Catalog", "#catalog"], ["Brands", "#brands"], ["Showroom", "#showroom"]].map(([label, href]) => <Anchor key={href} href={href} className="text-[10px] font-semibold uppercase tracking-[0.2em] text-[#2a211c]/70 transition-colors hover:text-[#a33b2d]">{label}</Anchor>)}<ArrowLink href="#inquiry">Start an inquiry</ArrowLink></nav><button type="button" aria-label={menuOpen ? "Close navigation" : "Open navigation"} aria-expanded={menuOpen} onClick={() => setMenuOpen(!menuOpen)} className="rounded-full p-2 md:hidden">{menuOpen ? <X size={20} strokeWidth={1.5} /> : <Menu size={20} strokeWidth={1.5} />}</button></div>{menuOpen && <nav className="mx-4 border-t border-[#2a211c]/10 bg-[#f3eee6] px-6 py-4 shadow-xl md:hidden">{["Catalog", "Brands", "Showroom"].map((label) => <Anchor key={label} href={`#${label.toLowerCase()}`} onClick={() => setMenuOpen(false)} className="block border-b border-[#2a211c]/10 py-4 text-xs font-semibold uppercase tracking-[0.18em]">{label}</Anchor>)}<Anchor href="#inquiry" onClick={() => setMenuOpen(false)} className="mt-5 inline-flex text-xs font-semibold uppercase tracking-[0.18em] text-[#a33b2d]">Start an inquiry <ArrowUpRight className="ml-2" size={15} /></Anchor></nav>}</header>
    <main>
      <section className="relative flex min-h-[700px] items-end overflow-hidden bg-[#d8cfc2] px-6 pb-16 pt-40 md:min-h-[820px] md:px-12 md:pb-24"><div className="absolute right-0 top-0 h-full w-[58%] md:w-[53%]"><img src={`${assetRoot}atc-showroom-wide.jpg`} alt="Material library and kitchen details in the ATC showroom" className="h-full w-full object-cover object-center" /><div className="absolute inset-0 bg-[#2a211c]/10 mix-blend-multiply" /></div><div className="relative z-10 mx-auto grid w-full max-w-[1440px] md:grid-cols-12"><div className="md:col-span-7"><Kicker>The ATC edit · 01 / 04</Kicker><h1 className="mt-7 max-w-[720px] font-serif text-[clamp(4rem,10vw,9.8rem)] leading-[0.82] tracking-[-0.065em]">Objects for<br /><em className="text-[#a33b2d]">living well.</em></h1><p className="mt-9 max-w-sm text-sm leading-6 text-[#2a211c]/70 md:ml-24">A considered catalog of kitchen systems, furniture fittings, and the small decisions that make a room feel resolved.</p><Anchor href="#catalog" className="mt-10 inline-flex items-center gap-3 text-[10px] font-semibold uppercase tracking-[0.2em] text-[#2a211c]">Browse the collection <ArrowDownRight size={17} className="text-[#a33b2d]" /></Anchor></div></div><span className="absolute bottom-6 right-6 text-[9px] uppercase tracking-[0.22em] text-[#2a211c]/50 md:right-12">Amman · Jordan</span></section>
      <section id="catalog" className="scroll-mt-10 px-6 py-24 md:px-12 md:py-36"><div className="mx-auto max-w-[1440px]"><div className="flex flex-col justify-between gap-8 md:flex-row md:items-end"><div><Kicker>The catalog</Kicker><h2 className="mt-6 font-serif text-5xl leading-[0.88] tracking-[-0.04em] md:text-8xl">Good materials.<br /><span className="text-[#a33b2d]">No noise.</span></h2></div><p className="max-w-xs text-sm leading-6 text-[#2a211c]/65">Selected for touch, tolerance, and a long life in the everyday. Ask us about the details behind each piece.</p></div><div className="mt-16 flex flex-wrap items-center gap-2 border-b border-[#2a211c]/15 pb-4"><span className="mr-5 text-[9px] uppercase tracking-[0.2em] text-[#2a211c]/45">Filter</span>{filters.map((item) => <button key={item} type="button" onClick={() => setFilter(item)} className={`mr-5 pb-1 text-[10px] uppercase tracking-[0.18em] transition-colors ${filter === item ? "border-b border-[#a33b2d] text-[#a33b2d]" : "text-[#2a211c]/55 hover:text-[#2a211c]"}`}>{item}</button>)}<span className="ml-auto hidden text-[9px] uppercase tracking-[0.18em] text-[#2a211c]/45 sm:block">{shown.length} selections</span></div><div className="mt-8 grid gap-x-5 gap-y-12 sm:grid-cols-2 lg:grid-cols-4">{shown.map((p, i) => <article key={p.name} className={i % 2 === 1 ? "lg:translate-y-12" : ""}><Anchor href="#inquiry" className="group block"><div className="relative aspect-[0.86] overflow-hidden bg-[#d6cdc1]"><img src={`${assetRoot}${p.image}`} alt={p.name} className="h-full w-full object-cover grayscale-[25%] transition-transform duration-700 group-hover:scale-105" /><div className="absolute inset-0 bg-[#2a211c]/10 mix-blend-multiply" /><span className="absolute left-4 top-4 h-3 w-3 rounded-full border border-[#f3eee6]/80" style={{ backgroundColor: p.tone }} /><span className="absolute bottom-4 right-4 flex h-9 w-9 items-center justify-center rounded-full bg-[#f3eee6]/90 opacity-0 transition-opacity group-hover:opacity-100"><Plus size={15} /></span></div><div className="mt-4 flex items-start justify-between gap-4"><div><h3 className="font-serif text-2xl">{p.name}</h3><p className="mt-1 text-[10px] uppercase tracking-[0.14em] text-[#2a211c]/50">{p.detail}</p></div><span className="pt-1 text-[9px] uppercase tracking-[0.15em] text-[#a33b2d]">{p.type}</span></div></Anchor></article>)}</div></div></section>
      <section id="brands" className="scroll-mt-10 bg-[#2a211c] px-6 py-24 text-[#f5eee5] md:px-12 md:py-32"><div className="mx-auto grid max-w-[1440px] gap-14 md:grid-cols-12 md:gap-8"><div className="md:col-span-4"><Kicker inverse>Our partners · 02 / 04</Kicker><h2 className="mt-7 font-serif text-5xl leading-[0.88] md:text-7xl">The names<br /><em className="text-[#d98c79]">behind</em> the work.</h2></div><div className="md:col-span-7 md:col-start-6 md:pt-14"><p className="max-w-lg text-xl leading-8 text-[#f5eee5]/70">We work with makers who share our standard: precise engineering, honest materials, and a respect for the way a room is actually used.</p><div className="mt-14 grid grid-cols-2 border-t border-[#f5eee5]/20 sm:grid-cols-3">{["Bora", "Blum", "Fenix", "Leicht", "Cosentino", "Häcker"].map((brand) => <div key={brand} className="border-b border-r border-[#f5eee5]/20 py-7 font-serif text-2xl text-[#f5eee5]/85">{brand}</div>)}</div><div className="mt-8"><ArrowLink href="#showroom">Meet the collection in person</ArrowLink></div></div></div></section>
      <section id="showroom" className="relative scroll-mt-10 overflow-hidden px-6 py-24 md:px-12 md:py-36"><img src={`${assetRoot}atc-hero-kitchen.jpg`} alt="Warm contemporary kitchen showroom" className="absolute inset-0 h-full w-full object-cover object-center" /><div className="absolute inset-0 bg-[#2a211c]/60" /><div className="relative z-10 mx-auto flex min-h-[390px] max-w-[1440px] flex-col justify-between text-[#f5eee5]"><div className="flex justify-between"><Kicker inverse>Now step inside · 03 / 04</Kicker><span className="text-[9px] uppercase tracking-[0.2em] text-[#f5eee5]/60">Al-Bayader / Al-Wehdat</span></div><div><h2 className="max-w-3xl font-serif text-5xl leading-[0.88] md:text-8xl">See it in the<br /><em className="text-[#d98c79]">right light.</em></h2><div className="mt-9"><Anchor href="#inquiry" className="group inline-flex items-center gap-3 border-b border-[#f5eee5]/60 pb-2 text-[10px] font-semibold uppercase tracking-[0.2em]">Plan a showroom visit <ArrowUpRight size={15} className="transition-transform group-hover:translate-x-1 group-hover:-translate-y-1" /></Anchor></div></div></div></section>
      <section id="contact" className="scroll-mt-10 bg-[#d9cfc2] px-6 py-24 md:px-12 md:py-36"><div className="mx-auto grid max-w-[1440px] gap-12 md:grid-cols-12"><div className="md:col-span-5"><Kicker>The conversation · 04 / 04</Kicker><h2 className="mt-7 font-serif text-5xl leading-[0.87] md:text-8xl">Bring us<br />the hard<br /><span className="text-[#a33b2d]">questions.</span></h2></div><div className="md:col-span-5 md:col-start-8 md:pt-24"><p className="text-xl leading-8 text-[#2a211c]/75">From first sketch to final fitting, our team helps architects and makers specify with confidence.</p><div className="mt-10 space-y-4 border-t border-[#2a211c]/20 pt-4"><Anchor href="#inquiry" className="group flex items-center justify-between border-b border-[#2a211c]/20 pb-4 text-lg">Send an inquiry <ArrowUpRight size={18} className="text-[#a33b2d]" /></Anchor><Anchor href="#inquiry" className="group flex items-center justify-between border-b border-[#2a211c]/20 pb-4 text-lg">Request a specification pack <ArrowUpRight size={18} className="text-[#a33b2d]" /></Anchor></div></div></div></section>
      <section id="inquiry" className="scroll-mt-10 bg-[#a33b2d] px-6 py-20 text-[#f5eee5] md:px-12 md:py-24"><div className="mx-auto flex max-w-[1440px] flex-col justify-between gap-9 md:flex-row md:items-end"><div><Kicker inverse>Have a project in mind?</Kicker><h2 className="mt-6 font-serif text-5xl leading-none md:text-7xl">Let's make room<br />for the details.</h2></div><Anchor href="mailto:hello@amara-trading.com" className="group inline-flex items-center gap-3 border-b border-[#f5eee5]/70 pb-2 text-[10px] font-semibold uppercase tracking-[0.2em]">Send an inquiry <ArrowUpRight size={15} /></Anchor></div></section>
    </main>
    <footer className="bg-[#e7ded3] px-6 py-10 md:px-12"><div className="mx-auto flex max-w-[1440px] flex-col gap-8 md:flex-row md:items-end md:justify-between"><div><Wordmark /><p className="mt-5 max-w-xs text-xs leading-5 text-[#2a211c]/55">Premium kitchen systems and furniture fittings, serving Jordan since 1977.</p></div><div className="text-[10px] uppercase tracking-[0.17em] text-[#2a211c]/55 md:text-right">Al-Bayader · Al-Wehdat · Amman<br /><span className="text-[#a33b2d]">Quiet authority in hardware.</span></div></div><div className="mx-auto mt-10 max-w-[1440px] border-t border-[#2a211c]/15 pt-5 text-[9px] uppercase tracking-[0.2em] text-[#2a211c]/45">© {new Date().getFullYear()} Amara Trading Center</div></footer>
  </div>;
}